/**
 * Enumerates machine-readable error codes used in API responses.
 */
export const ERROR_CODES = Object.freeze({
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  AUTH_HEADER_MISSING: 'AUTH_HEADER_MISSING',
  TOKEN_INVALID: 'TOKEN_INVALID',

  // Auth/User
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_IN_USE: 'EMAIL_IN_USE',

  // Catalog
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',
  BRAND_NAME_IN_USE: 'BRAND_NAME_IN_USE',
  BRAND_SLUG_IN_USE: 'BRAND_SLUG_IN_USE',
  BRAND_HAS_PRODUCTS: 'BRAND_HAS_PRODUCTS',
  ATTRIBUTE_NOT_FOUND: 'ATTRIBUTE_NOT_FOUND',
  ATTRIBUTE_NAME_IN_USE: 'ATTRIBUTE_NAME_IN_USE',
  ATTRIBUTE_SLUG_IN_USE: 'ATTRIBUTE_SLUG_IN_USE',
  OPTION_NOT_FOUND: 'OPTION_NOT_FOUND',
  OPTION_NAME_IN_USE: 'OPTION_NAME_IN_USE',
  OPTION_SLUG_IN_USE: 'OPTION_SLUG_IN_USE',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  VARIANT_COMBINATION_IN_USE: 'VARIANT_COMBINATION_IN_USE',
  VARIANT_COMBINATION_INVALID: 'VARIANT_COMBINATION_INVALID',
  SKU_IN_USE: 'SKU_IN_USE',
  INVALID_SKU: 'INVALID_SKU',
  PRODUCT_HAS_INVENTORY: 'PRODUCT_HAS_INVENTORY',
  PRODUCT_HAS_REVIEWS: 'PRODUCT_HAS_REVIEWS',
  PRODUCT_IN_ORDERS: 'PRODUCT_IN_ORDERS',
  PRODUCT_IN_SHIPMENTS: 'PRODUCT_IN_SHIPMENTS',

  // Cart
  CART_EMPTY: 'CART_EMPTY',
  ITEM_NOT_IN_CART: 'ITEM_NOT_IN_CART',
  QUANTITY_POSITIVE: 'QUANTITY_POSITIVE',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',

  // Orders
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND'
});
